GET http://localhost:8080/tasks

###
POST http://localhost:8080/tasks/create
Content-Type: application/json

{
    "text":"breakfast"
}

###
DELETE http://localhost:8080/tasks/delete/612e3eb3e73371b3df6fb98f

###
PATCH http://localhost:8080/tasks/update/6126422222870c097253cc42
Content-Type: application/json

{
        "done": false
}

###
GET http://localhost:8080/columns

###
POST http://localhost:8080/columns/create
Content-Type: application/json

{
    "title": "home",
    "taskIds": ["612e3ea2e73371b3df6fb989", "612e3eade73371b3df6fb98c", "612e3eb3e73371b3df6fb98f"]
}

###
PATCH http://localhost:8080/columns/remove-task/612f7ad8f038882abab1305e
###
DELETE http://localhost:8080/columns/delete/6128eed1882411849d3ad3eb

###
PATCH http://localhost:8080/columns/update/612e40defefe29b813243b06
Content-Type: application/json

{
    "title": "home",
    "taskIds": ["612e3ea2e73371b3df6fb989", "612e3eade73371b3df6fb98c", "612e3eb3e73371b3df6fb98f"]
}
###
PATCH http://localhost:8080/columns/remove-task/61279121db84bbff7adb5a93
###
GET http://localhost:8080/column-order

###
POST http://localhost:8080/column-order/create
Content-Type: application/json

{
    "columnOrder": [ "6128eed1882411849d3ad3eb","6128dfe54c5a2e7daa9af183"]
}

###
DELETE http://localhost:8080/column-order/delete/6128eede882411849d3ad3ed

###
PATCH http://localhost:8080/column-order/update/6128f05050dc72853b6a9487
Content-Type: application/json

{
    "columnOrder": ["6128dfe54c5a2e7daa9af183", "612e40defefe29b813243b06"]
}
